- domain: .xuexi.cn
  expiry: 5291507202048000
  httpOnly: false
  name: __UID__
  path: /
  secure: false
  value: ce7aebb0-a890-11e9-b116-57c52e5e042e
- domain: .xuexi.cn
  expiry: 37521901896
  httpOnly: false
  name: zwfigprt
  path: /
  secure: false
  value: 1b55c70efe63ac919fb13aca0721d995
- domain: .xuexi.cn
  expiry: 37521901896
  httpOnly: false
  name: tmzw
  path: /
  secure: false
  value: '1563369379394'
- domain: .xuexi.cn
  httpOnly: false
  name: uaToken
  path: /
  secure: false
  value: 115#13cCU11O1TZL180pTCdY1CsoNlCGB9A1dg2mOh2/D51E2hd1uRqY11tup6ECyzewASfPeBL8ukNQi/JJhaUzAkdDaLBXy51QOSfyeKhG16NQiQXR3Wz/vBNDaGwfurrQOSfyeKT4kkNdi/JJhUU8AkNDaL6AurPQi7S73DfGO6F65jeQSFAFFKjH17Qffq4xHYqjMxk+fnRsvWbNdvn0u5O2M0zt8kCVOhykDWb2iN7UaCwKmUPDQV9N8YOVn7pJ11+H7sJ8O+UP55fAWQ3QPctZ07PkaZqgJsqPV6MznPcXlLBjNoyb8fgzSnSX/Q0IVm/tzWaxUm2+y6cDyVALwUVZ5NFxKNOhUAGv4ZHkzirgVSnALVeEQOEsM2dKQ7mZvzs921doYpPsbJRK/Iinofvj5SwbR1wK7WGlzt3zJUn1nmpsyYBMEmgcZ8nZ+mh8W9MyhGVkbOoEJvK1x4XaL00AiFv1lS1tvekp5SUBmD+1YPFulOinOqxIVn0TLQuTxdj1cbXQap9bmqlNLNm++P+wT2iYR5UOnEnSz40KuMPlzk2V8Vws0PCy+AYbP/ewAV1CSY7sdArQv7lUjgOjf+rKxR0Qv5==
- domain: .xuexi.cn
  expiry: 37521383520
  httpOnly: false
  name: token
  path: /
  secure: false
  value: 8ff671cb34184cfea805cced64ebe18e
- domain: .xuexi.cn
  httpOnly: false
  name: webUmidToken
  path: /
  secure: false
  value: TE13A155996172A630B70D86814C3D5635FD2BDE20C1D1B48CF5D109A6B
