- domain: .xuexi.cn
  expiry: 15948993680000
  httpOnly: false
  name: __UID__
  path: /
  secure: false
  value: 11f4ad90-a887-11e9-8bb8-1f4db7d2f928
- domain: .xuexi.cn
  expiry: 156340683800
  httpOnly: false
  name: zwfigprt
  path: /
  secure: false
  value: f84c457e8079e5edaec3ea23c6baf626
- domain: .xuexi.cn
  expiry: 156340683800
  httpOnly: false
  name: tmzw
  path: /
  secure: false
  value: '1563363638675'
- domain: .xuexi.cn
  httpOnly: false
  name: uaToken
  path: /
  secure: false
  value: 115#1F6R051O1TarZLz0TCdY1CsoNlCGB9A1dg2mOh2/D51E2hd1uRqY11tup6ECyze6ASfPeQ88ukNQi/JJhaUzAkdDaLBXy51QOSfyeKhG16NQiQXR3Wz/vBNDaGwfurrQOSfyeKT4kkNdi/JJhUU8AkNDaL6AurPQi7S73DfGO6F65jeQSFAFFKjH17Qffq4xHYqjMxk+f3NsYGbNdvn0u5O2Gl/bidL2AJvbsk8Ua6EKQnoaih3MLjco3IMxdbXLyMJIyXBHfGO1unlCZCz1fnBApoh0Rhe81HgEhzlPfvcPOYsHR6/wjieSNP85T4ddwqMQJPn2OCyGPOZKQOuFlr0fg9oVgwTkJm29QPtQdD+hI9bVWBmQml4ID2saMZKRKrThgRxYagNy0wXTUdX9CINwp6rsHh+O+dN5Ao6ucu7tciOyu87dVL75QZaVSPCqBCH7MCrnsb42+JSFpGi7NDYzQrZba5/DcvYXYIasz1zIA3c1u1u+leIpvk8UoaC443aQV3DyV5usKo/r84EWNgj+5Q4wSIQ8LOIc2AuFu18gVIXKxqtJdcdfaV/uFE9TKe+pPQHF0N1Y6GDKqbF3zav2TUw6BxErF5rqq5==
- domain: .xuexi.cn
  expiry: 156338523900
  httpOnly: false
  name: token
  path: /
  secure: false
  value: cc90ed1a8a1146bd8254eec02835c3a0
- domain: .xuexi.cn
  httpOnly: false
  name: webUmidToken
  path: /
  secure: false
  value: TC4B5951223A1AD845F708DCE59B8B47A75C4E28B012EBC99B18E99D09E
