- domain: .xuexi.cn
  expiry: 1594987590
  httpOnly: false
  name: __UID__
  path: /
  secure: false
  value: 7a20d5b0-a954-11e9-a983-a19ddc4e1a6f
- domain: .xuexi.cn
  expiry: 1563494798
  httpOnly: false
  name: zwfigprt
  path: /
  secure: false
  value: 1474b6d44c783b8adaedf47c1d10c0d5
- domain: .xuexi.cn
  expiry: 1563494798
  httpOnly: false
  name: tmzw
  path: /
  secure: false
  value: '1563451598936'
- domain: .xuexi.cn
  httpOnly: false
  name: uaToken
  path: /
  secure: false
  value: 115#1Ftiqf1O1TNDKLEDTCdY1CsoNlCGB9A1dg2mOh2/D51E2hd1uRqY11tupXjcyzUJASfPeK1KykNQi/JJhUU8AWCcZTBXurrQOSAyeKT8G6KdiQJRHZyhX21VaLBfDzFQOSfyeKT8uWNIi/yJhUU4AkNcaTBXs61QOSAwhErl2WKp95TsMJaMSBWWnMA/wZssorHxEoGx3Yn6Vfih0NWIpm441IR+fR6eeKoPyqwHu9+fKnWPfSvp7NxqGIRbwvfgg2n4g05exaNcjE9RDZC3Md0oVGei/2ayY//z4/70HncpA2Q3c4wfLVj2iY/sP8i9nQVuj4CiRKGidvNywpMWWzIqx9QoCe59dhLj0shNIELhI6EyvnC4LKvBONVqO18A21bu4q0nrGOwhvmP5I3xtImYcQvtHZ3MctfVw9ApR3Vc0orLEzQfGc+oP/LDXp9NKtz7ZzdvEd7vEyPDvHsvhSJVi9RApOPfZcehvMahN1w38QXHXLq53Z/2uh9aQg25rcGghTG8Sq8nLgdzBKe+7H3YFuhlNNW1j4GQbOezkpbVvrhwPrtbxKMp4f6SR8/j2AmC9e+yVh3ZmHqu7uvydWFkUlpyrTDrEWp2jaV=
- domain: .xuexi.cn
  expiry: 1563473200
  httpOnly: false
  name: token
  path: /
  secure: false
  value: 4e9bd050915c45e4858b8ed254f002d2
- domain: .xuexi.cn
  httpOnly: false
  name: webUmidToken
  path: /
  secure: false
  value: T72FCB8F61000622E7531857CD3867947076DE2CD85D7F2733FA3192DB5
